export {default as cinema_icon} from './cinema_icon.png'
export {default as profile_icon} from './profile_icon.png'
export {default as prospects_icon} from './prospects_icon.png'
export {default as rating_icon} from './rating_icon.png'
export {default as store_icon} from './store_icon.png'
export {default as zoom_icon} from './zoom_icon.png'