export {default as cinema} from './cinema.png'
export {default as rating} from './rating.png'
export {default as rocket} from './rocket.png'
export {default as store} from './store.png'
export {default as student} from './student.png'
export {default as zoom} from './zoom.png'